### ISSUE TITLE
documentation incomplete + temperature bug

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#10]
`int PozyxClass::getTemperature_c(float32_t *temperature, uint16_t remote_id)`

seems to return 0. Also the online documentation doesn't contain much.

**Comment by lpdunwell** [comment]
on the website i see the temperature is unsupported in FW v0.9.
reading the FW version from the shield returns '1'.

**Comment by samuelvdv** [comment]
Hi, 
This is an issue with the firmware version which has the value '1' for version v0.9. This should be '9'.
The next firmware version will follow the correct numbering format: v{MAJOR}.{MINOR} and also correctly fill the temperature register.

**Comment by lpdunwell** [comment]
Great! thanks for the fixes! When will the fw be released?

**Comment by samuelvdv** [comment]
Hi!
We hope this week but if not, then definitely still this month.
Thanks for all your comments by the way! We appreciate it.

**Comment by lpdunwell** [comment]
Great!
Thanks. Just trying to help, as we basically have something relying on posyx and lose a lot of time if we need to reinvent the wheel... :D
