### ISSUE TITLE
Reset faulty

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#14]
`Pozyx.resetSystem();`
makes the Pozyx shield fall into a 'reset-loop', from which it doesn't recover.

**Comment by lpdunwell** [comment]
Actually after playing around a little, I found out by disconnecting the reset line from the arduino prevents it from looping and i get an error. This means that calling Pozyx.resetSystem(); fails and then resets the arduino. This must not happen.

**Comment by samuelvdv** [comment]
Hi, this is a known issue and is already fixed for the future firmware release.
Thank!
