### ISSUE TITLE
another way to completely crash Pozyx

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#17]
`Pozyx.regRead(0xB2, &data, 1);`
Of course this makes little sense, as this is the register function address of 'POZYX_TX_DATA',
but the fact that this completely freezes up the module. Sanity check of some kind?

**Comment by lpdunwell** [comment]
*or timeout

**Comment by samuelvdv** [comment]
Hi, 
this register is indeed not intended to be read from.
I have fixed this and now it will give an error with the code 0x0D (POZYX_ERROR_FUNC_PARAM) indicating that some parameters should be added before data can be read.
The fix will be available in the next firmware release. 
Thanks
