### ISSUE TITLE
Random errors: getTxPower

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#24]
> ERROR: getTxPower
> Error 0x09: Flash memory is corrupted or invalid

this happened a couple of times, and i'm pretty certain this is not the case because:

- it's not exactly repeatable
- the things still seem to respond

I have no access to the fw source, so I'll just keep the weird bug reports rolling.
maybe someone else has and idea...

**Comment by samuelvdv** [comment]
Hi, 
this is an error you can ignore, it's not important and it doesn't affect the pozyx functionality.
