### ISSUE TITLE
getCalibrationStatus unexpected results

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#26]
basically for mag and sys status there can also be 1 or 2. possibly same for acc and gyr.

**Comment by samuelvdv** [comment]
The value 0 means no calibration information is present, a value of 3 means fully calibrated.
The intermediary values mean the system is partially calibrated. For example, with the accelerometer, it is required to stabilize the tag in different orthogonal planes. The calibration number will go up to 1 then 2 and 3 after stabilizing in these planes. 
For most purposes, however, a value of 0 denotes that the sensor should not be relied upon. Any value above 0 is ok, with 3 being the ideal number.
