### ISSUE TITLE
calibration status

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#32]
since fw v1.0 i cannot get the ACC to calibrate anymore.
orientation_3d shows how it believes to tilt away in random directions when lifted in Z axis.

**Comment by samuelvdv** [comment]
Hello,

I have reproduced your setup and after a while the ACC did calibrate (after sufficient movement of the tag). As long as the sensors are not all calibrated, some unexpected behavior such as you describe, can be seen. 
However, I must agree with you that calibration sometimes takes long, and I have added a todo topic to the next firmware release to save the calibration profile once it is fully calibrated. This should speed up the calibration process on the next startup of the Pozyx device.
