### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by qdzhaozx** [pozyxLabs/Pozyx-Arduino-library#38]
Can you set codes indented with Tabs ?? And one Tab be equals to four spaces.
It's somewhat weird that the codes indented with two spaces.

Best regards

**Comment by lpdunwell** [comment]
i believe using two spaces instead of a tab for indenting is what you'll find in a majority of places on the internet. any major editor can automatically convert between the two.

**Comment by laurentva** [comment]
As Luke has said, 2 spaces is quite common and any major editor can easily convert between tabs and spaces, and you can configure whether a tab is 2 or 4 spaces therein. For our Arduino library we'd like to remain consistent with two-space indentation.
