### ISSUE TITLE
UWBConfigurator stuck on Arduino Tian

### ISSUE THREAD

**Issue by laurentva** [pozyxLabs/Pozyx-Arduino-library#39]
The UWBConfigurator lists the following output:

```
Perform scanning
---------------------------------------------------------

Local device: 
--
1) 0x6F5E: channel 5   - bitrate: 110kbit/s - PRF: 64MHz - plen: 1024

Scanning remote devices..

Channel: 1
```

And here it gets stuck. Looking at the code, I assume the Tian crashes when going through the different UWB settings when trying to discover all the devices. 
On Uno, however, this works fine.

**Comment by samuelvdv** [comment]
It appears that __attribute__((packed)) does not work as expected on the TIAN in the definition of the _UWB_settings struct, at least not in combination with floats. I have adjusted the library so it no longer uses the packed attribute and that it works on the TIAN.
