### ISSUE TITLE
can multi-tag send the sensor data(acceleration, gyro) to master tag

### ISSUE THREAD

**Issue by kitylam9** [pozyxLabs/Pozyx-Arduino-library#42]
if it is not possible, how do we set the multi-tag positioning work for directly send through serial

**Comment by laurentva** [comment]
Hey,

Sure, this can be done by performing getAcceleration_mg(&acceleration, remote_id); and getAngularVelocity_dps(&angular_vel, remote_id); after doRemotePositioning(remote_id, &coordinates); 

A tutorial for multitag will come online next week, including how to get additional data from remote tags. If you have questions about pozyx and not per se issues with the Arduino library, please mail support@pozyx.io in the future.
