### ISSUE TITLE
POZYX_DEVICE_GETINFO doesn't return the "Special flag describing the device"

### ISSUE THREAD

**Issue by jakemagee** [pozyxLabs/Pozyx-Arduino-library#50]
When executing the POZYX_DEVICE_GETINFO function, I don't appear to be getting the 3rd byte, "Special flag describing the device", as described in the register overview documentation.  I appear to get a success/failure byte, and then the device address bytes.

**Comment by samuelvdv** [comment]
The first byte is indeed a success/failure byte (I have changed this in the documentation). However, the following bytes should be the information about the device as is listed in the documention.
Best regards,
