### ISSUE TITLE
Inconsistent POZYX_INT_STATUS FUNC bit from POZYX_DEVICES_GETIDS

### ISSUE THREAD

**Issue by jakemagee** [pozyxLabs/Pozyx-Arduino-library#51]
When I add devices to the internal list via a call to POZYX_DEVICES_DISCOVER, POZYX_DEVICES_GETIDS will set the FUNC bit in POZYX_INT_STATUS.  However, when I add devices via a call to POZYX_DEVICE_ADD, POZYX_DEVICES_GETIDS will not set the FUNC bit.  Is this expected?

**Comment by samuelvdv** [comment]
Hello,
the function bit will let you know that the POZYX_DEVICES_DISCOVER has finished its functionality. This is because the discovery can take a longer time. POZYX_DEVICE_ADD, and POZYX_DEVICES_GETIDS don't generate a FUNC because it's instantaneous.
