### ISSUE TITLE
Tag version does not match library.properties

### ISSUE THREAD

**Issue by njh** [pozyxLabs/Pozyx-Arduino-library#53]
Hello,

I maintain http://www.arduinolibraries.info/

I noticed that your library has just been added to the Arduino Library Manager. However the version number in library.properties does not match the tag you used:

https://github.com/pozyxLabs/Pozyx-Arduino-library/tree/v0.9.0

Please can you correct or create a new tag?

Thanks!

nick.

**Comment by laurentva** [comment]
Fixed! Thanks!
