### ISSUE TITLE
POZYX_DEVICES_CALIBRATE issues

### ISSUE THREAD

**Issue by jakemagee** [pozyxLabs/Pozyx-Arduino-library#54]
When trying to use the POZYX_DEVICES_CALIBRATE function, I get the error code 0x17 alot.  Can you explain what this error is?  It isn't documented in the register overview.

It also appears that the optional input parameters are not actually optional.  I can't get the function to stop generating error code 0x17 unless I at least supply the first 8 bytes worth of input parameters.

And the register overview description states that "At the end of calibration the corresponding bit in the POZYX_CALIB_STATUS register will be set"... can you clarify what bit that refers to?

And the POZYX_DEVICES_CALIBRATE function doesn't set the FUNC bit in the POZYX_INT_STATUS register when it has completed.  How can we determine when the calibration is complete (unless there is actually a calibration bit that gets set somewhere)?

And lastly, the register overview notes POZYX_DEVICES_CALIBRATE as having 1 input parameter byte... this appears to be incorrect.

**Comment by AlexisTM** [comment]
Dear @jakemagee,

POZYX_CALIB_STATUS is unrelated to POZYX_DEVICES_CALIBRATE. The first is for the IMU and the second for the positionning. I don't know anything about the return code. :/

See [registers](https://www.pozyx.io/Documentation/Datasheet/RegisterOverview)
