### ISSUE TITLE
Which algorithms are implemented

### ISSUE THREAD

**Issue by AlexisTM** [pozyxLabs/Pozyx-Arduino-library#55]
Dear,

There are 3 algorithms in the definitions. 

Which of those are implemented?

* POZYX_POS_ALG_UWB_ONLY = 0
* POZYX_POS_ALG_TRACKING = 1
* POZYX_POS_ALG_LS = 2

**Comment by samuelvdv** [comment]
Hello,

The POZYX_POS_ALG_UWB_ONLY and POZYX_POS_ALG_LS are currently available in both 2D and 3D. The POZYX_POS_ALG_TRACKING is currently under test and will arrive in the next firmware update.

Best Regards,

**Comment by AlexisTM** [comment]
Thanks

**Comment by sveinolavhegerland** [comment]
Hello,

what sort of algorithm is POZYX_POS_ALG_UWB_ONLY? Is it some kind of Linear Least Squares (LLS), Non LLS, Cayley-menger etc. ?  The same for POZYX_POS_ALG_LS = 2??

Thanks in advance!

**Comment by AlexisTM** [comment]
* POZYX_POS_ALG_UWB_ONLY: No post processing
* POZYX_POS_ALG_TRACKING: Using IMU
* POZYX_POS_ALG_LS: Least squares
