### ISSUE TITLE
Pozyx IMU coordinate frame ENU or NED?

### ISSUE THREAD

**Issue by AlexisTM** [pozyxLabs/Pozyx-Arduino-library#62]
Dear,

I would like to know which is the frame coordinate frame of the Pozyx IMU. Is it a ENU or NED coordinate frame?

**Comment by samuelvdv** [comment]
Hello,

The axes of the (local) coordinate system are printed on the board. This is the right-hand rule, similar to ENU. The angle towards the magnetic north is given with respect to the x-axis.

Hope this helps.
