### ISSUE TITLE
[Feature] Localization of any number of tags at high frequency

### ISSUE THREAD

**Issue by AlexisTM** [pozyxLabs/Pozyx-Arduino-library#65]
Would it be on your roadmap to implement a GPS like protocol for the DWM1000?

This requires:
* Synchronizing the timestamps of all devices;
* Each anchor send its position and current timestamp;
* From the positions and timestamps received, the devices compute their position.

Pros:
* Works with any number of tags are they are in "listening only" mode;
* Adding an anchor do not require to change the configuration of each tag;
* The tags are "stupid" and thus do not need more configuration than the band, power, ... and can join any network seamlessly.

Cons: 
* The timestamp synchronization must be precise;
* The anchors must send their messages in a synchronous way.

**Comment by samuelvdv** [comment]
Hello, 
this is indeed possible. The requirements for synchronization between the anchors are however very demanding and is hard to fit on the current Pozyx anchors. (Note that the DWM1000 alone is also not capable of this). The past year we have been developing such a system with the first pilot installations started last summer giving very good results. We are expecting to launch this early 2018. Please contact sales@pozyx.io if you interested in more details.
