### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by tommitytom** [pozyxLabs/Pozyx-Arduino-library#66]
The documentation for the doPositioning() function has this line:
`On its way to deprecation, use setPositionAlgorithm once and new doPositioning instead`
What does this mean exactly?  What is being deprecated and what should I be using?

**Comment by laurentva** [comment]
Hey Tom, you're right! Seems like I commented the wrong functions which were leftover from some of my ambitions. Thanks for pointing that out! I'll change it right now.

**Comment by vidmera** [comment]
The code won't compile because the definition function doPositioning(...) is not consistent.
