### ISSUE TITLE
getAnchorIds doesn't get anchor ids

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#7]
`Pozyx.doDiscovery(POZYX_DISCOVERY_ALL_DEVICES, 5, 10);
Pozyx.getAnchorIds(anchors, listsize);`
this results in listsize = 5 and all entries in the anchors array to be 0.
however replacing getAnchorIds with getDeviceIds makes it work.

**Comment by samuelvdv** [comment]
Hi, this should be fixed now: referring to issue #11
The same is fixed for getTagIds()
Thank you for reporting this issue!
