### ISSUE TITLE
Get Distance from Anchors

### ISSUE THREAD

**Issue by marcoareis** [pozyxLabs/Pozyx-Arduino-library#71]
Hello, I am wondering if there is any function which can give me the distance (in mm) from the pozyx tag to an anchor (or more than one).

I guess the "doAnchorCalibartion()" function does something related to that, but shows me nothing but the anchor positions that I manually measured and set. I know that the 3 algorithms (UWB, LS and TRACKING) you have, take these distances and perform the calculation on the background, in order to get the position.

My question is if there is any possibility of getting this 4 distances? (in the case of using 4 anchors)

Thanks in advance!

**Comment by laurentva** [comment]
Hey Marco,

I hope [this tutorial](https://www.pozyx.io/Documentation/Tutorials/ready_to_range) answers your question! Please contact support@pozyx.io in the future for questions like these :smile:
