### ISSUE TITLE
Problem running ready_to_range

### ISSUE THREAD

**Issue by florianspy** [pozyxLabs/Pozyx-Arduino-library#77]
I have connected the pozyx node via usb to a Ubuntu 16.04 PC, when i run ready_to_range.py i get the following error: 
ERROR Ranging, local ERROR 0x12: Ranging timeout
When i am using the same setup in Windows with the provided software to show the data everything works fine

**Comment by laurentva** [comment]
Did you correctly set the same parameters in your script? Are you running it on Ubuntu and Windows at the same time? Please continue at support@pozyx.io

**Comment by florianspy** [comment]
i am running it on the same machine with dual Boot,
 one with Windows OS and one with Ubuntu.
i guess this problem might also be related to the python3 issue?
