### ISSUE TITLE
Time synchronization

### ISSUE THREAD

**Issue by kungfupizza** [pozyxLabs/Pozyx-Arduino-library#85]
Hi,
If I have more than 3(even more than 20) tags, how do I synchronize the tags to avoid collision? Is there a Timeslot allocation done in the configurator?

**Comment by laurentva** [comment]
Hi, 

You can use the [multitag example](https://github.com/pozyxLabs/Pozyx-Arduino-library/blob/master/examples/multitag_positioning/multitag_positioning.ino) or follow the[ tutorial](https://www.pozyx.io/documentation/creator/arduino/multitag-positioning) to see how positioning multiple tags at once would work.

Please direct your query to support@pozyx.io next time, as this isn't part of the code.

Kind regards,
