### ISSUE TITLE
Unit tests folder mislabeled

### ISSUE THREAD

**Issue by lpdunwell** [pozyxLabs/Pozyx-Arduino-library#9]
arduino ide doesn't like the fact that the folder is not called like the sketch (also there's a typo in the folder name)

**Comment by samuelvdv** [comment]
Hello, 
It looks like I had too much c in my fingers calling the folder uint :)
I have renamed it an created a folder with the same name as the sketch. This leaves room for future sketches for unit tests.
Concerning the unit tests, I believe that your stress test pull request should actually be in the unit tests folder. This way we can keep the examples folder in line with the examples/tutorials on the pozyx website.
